# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WagCodingChallenge' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WagCodingChallenge
  pod 'SDWebImage'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'


end
